# Generated by Django 2.1.3 on 2018-11-20 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('TD', 'todo'), ('IP', 'in-progress'), ('DN', 'done')], default='TD', max_length=2)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
